CREATE USER postgres WITH PASSWORD 'WedbGf3a6ZHF3NwdKzGy';

CREATE DATABASE clinica-medica;

-- public."Medico" definition

CREATE TABLE public."Medico" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	usuario text NULL,
	senha text NULL,
	nome text NOT NULL,
	sexo bpchar(1) NULL,
	registrocrm text NOT NULL,
	especialidade text NULL,
	telefone text NULL,
	CONSTRAINT "PK_medico" PRIMARY KEY (id)
);
CREATE UNIQUE INDEX "IX_Medico_usuario" ON public."Medico" USING btree (usuario);
CREATE UNIQUE INDEX "IX_medico_registoCrm" ON public."Medico" USING btree (registrocrm);

-- public."Paciente" definition
CREATE TABLE public."Paciente" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	usuario text NULL,
	senha text NULL,
	nome text NOT NULL,
	cpf text NOT NULL,
	sexo bpchar(1) NULL,
	idade int4 NOT NULL,
	telefone text NULL,
	email text NULL,
	endereco text NULL,
	CONSTRAINT "PK_paciente" PRIMARY KEY (id)
);
CREATE UNIQUE INDEX "IX_paciente_cpf" ON public."Paciente" USING btree (cpf);
CREATE UNIQUE INDEX "IX_paciente_usuario" ON public."Paciente" USING btree (usuario);

-- public."Recepcionista" definition
CREATE TABLE public."Recepcionista" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	usuario text NULL,
	senha text NULL,
	nome text NOT NULL
);
CREATE UNIQUE INDEX "IX_Recepcionista_usuario" ON public."Recepcionista" USING btree (usuario);

-- public."Laboratorio" definition
CREATE TABLE public."Laboratorio" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	usuario text NULL,
	senha text NULL,
	nome text NOT NULL,
	endereco text NULL,
	telefone text NULL,
	CONSTRAINT "PK_laboratorio" PRIMARY KEY (id)
);
CREATE UNIQUE INDEX "IX_Laboratorio_usuario" ON public."Laboratorio" USING btree (usuario);

CREATE TABLE public."Consulta" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	paciente_id int4 NOT NULL,
	medico_id int4 NOT NULL,
	"data" date NOT NULL,
	horario time NOT NULL,
	telefone text NULL
);

ALTER TABLE public."Consulta" ADD CONSTRAINT "FK_consulta_medico_medico_id" FOREIGN KEY (medico_id) REFERENCES public."Medico"(id) ON DELETE RESTRICT;
ALTER TABLE public."Consulta" ADD CONSTRAINT "FK_consulta_paciente_paciente_id" FOREIGN KEY (paciente_id) REFERENCES public."Paciente"(id) ON DELETE RESTRICT;


CREATE TABLE public."Exame" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	paciente_id int4 NOT NULL,
	medico_id int4 NOT NULL,
	laboratorio_id int4 NOT NULL,
	datasolicitacao date NOT NULL,
	tipo text NULL,
	dataresultado date NULL,
	resultado text NULL,
	disponivelonline bool NOT NULL DEFAULT false,
	entreguepaciente bool NOT NULL DEFAULT false
);
ALTER TABLE public."Exame" ADD CONSTRAINT "FK_exame_laboratorio_laboratorio_id" FOREIGN KEY (laboratorio_id) REFERENCES public."Laboratorio"(id) ON DELETE RESTRICT;
ALTER TABLE public."Exame" ADD CONSTRAINT "FK_exame_medico_medico_id" FOREIGN KEY (medico_id) REFERENCES public."Medico"(id) ON DELETE RESTRICT;
ALTER TABLE public."Exame" ADD CONSTRAINT "FK_exame_paciente_paciente_id" FOREIGN KEY (paciente_id) REFERENCES public."Paciente"(id) ON DELETE RESTRICT;

-- public."HistoricoPaciente" definition
CREATE TABLE public."HistoricoPaciente" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	paciente_id int4 NOT NULL,
	medico_id int4 NOT NULL,
	"data" date NOT NULL,
	descricao text NULL,
	CONSTRAINT "PK_historico" PRIMARY KEY (id)
);
ALTER TABLE public."HistoricoPaciente" ADD CONSTRAINT "FK_historico_medico_medico_id" FOREIGN KEY (medico_id) REFERENCES public."Medico"(id) ON DELETE RESTRICT;
ALTER TABLE public."HistoricoPaciente" ADD CONSTRAINT "FK_historico_paciente_paciente_id" FOREIGN KEY (paciente_id) REFERENCES public."Paciente"(id) ON DELETE RESTRICT;

INSERT INTO public."Medico"
(usuario, senha, nome, sexo, registrocrm, especialidade, telefone)
VALUES
  ('medico1', 'senha1', 'Dr. João Silva', 'M', '12345/SP', 'Cardiologia', '(00) 0000-0001'),
  ('medico2', 'senha2', 'Dra. Maria Santos', 'F', '67890/RJ', 'Dermatologia', '(00) 0000-0002'),
  ('medico3', 'senha3', 'Dr. André Souza', 'M', '54321/MG', 'Ortopedia', '(00) 0000-0003'),
  ('medico4', 'senha4', 'Dra. Ana Costa', 'F', '09876/SP', 'Ginecologia', '(00) 0000-0004'),
  ('medico5', 'senha5', 'Dr. Pedro Almeida', 'M', '43210/RJ', 'Pediatria', '(00) 0000-0005'),
  ('medico6', 'senha6', 'Dra. Carla Mendes', 'F', '76543/MG', 'Psiquiatria', '(00) 0000-0006'),
  ('medico7', 'senha7', 'Dr. Rafael Lima', 'M', '21098/SP', 'Oftalmologia', '(00) 0000-0007'),
  ('medico8', 'senha8', 'Dra. Laura Fernandes', 'F', '98765/RJ', 'Oncologia', '(00) 0000-0008'),
  ('medico9', 'senha9', 'Dr. Gabriel Santos', 'M', '32109/MG', 'Urologia', '(00) 0000-0009'),
  ('medico10', 'senha10', 'Dra. Rafaela Costa', 'F', '65432/SP', 'Endocrinologia', '(00) 0000-0010');

INSERT INTO public."Laboratorio"
(usuario, senha, nome, endereco, telefone)
VALUES
  ('lab1', 'senha1', 'Laboratório Alpha', 'Rua A, 123', '(00) 0000-0001'),
  ('lab2', 'senha2', 'Laboratório Beta', 'Avenida B, 456', '(00) 0000-0002'),
  ('lab3', 'senha3', 'Laboratório Gamma', 'Travessa C, 789', '(00) 0000-0003'),
  ('lab4', 'senha4', 'Laboratório Delta', 'Rua D, 321', '(00) 0000-0004'),
  ('lab5', 'senha5', 'Laboratório Epsilon', 'Avenida E, 567', '(00) 0000-0005'),
  ('lab6', 'senha6', 'Laboratório Zeta', 'Rua F, 987', '(00) 0000-0006'),
  ('lab7', 'senha7', 'Laboratório Eta', 'Avenida G, 654', '(00) 0000-0007'),
  ('lab8', 'senha8', 'Laboratório Theta', 'Travessa H, 321', '(00) 0000-0008'),
  ('lab9', 'senha9', 'Laboratório Iota', 'Rua I, 654', '(00) 0000-0009'),
  ('lab10', 'senha10', 'Laboratório Kappa', 'Avenida J, 123', '(00) 0000-0010');

INSERT INTO public."Recepcionista" (usuario, senha, nome)
VALUES
  ('recepcionista1', 'senha123', 'Maria Silva'),
  ('recepcionista2', 'senha456', 'João Santos'),
  ('recepcionista3', 'senha789', 'Ana Pereira'),
  ('recepcionista4', 'senhaabc', 'Pedro Oliveira'),
  ('recepcionista5', 'senhaxyz', 'Carla Souza'),
  ('recepcionista6', 'senha123', 'Luiz Ferreira'),
  ('recepcionista7', 'senha456', 'Fernanda Rodrigues'),
  ('recepcionista8', 'senha789', 'Ricardo Almeida'),
  ('recepcionista9', 'senhaabc', 'Mariana Costa'),
  ('recepcionista10', 'senhaxyz', 'Gabriel Santos');
